#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 2c5d0442-6b3e-4d5f-bece-69bb63cee7d2
# Source File: RestoreForm.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
rhQAAB+LCAAAAAAABADNWG1v2jAQ/j5p/8HKviIghPAiQSTIWqla21WFdftWOclBvToxcpyW7Nfv
AqHQ8uYwQBMSIsHn5+6e586XdO7BFy8g069UUYI/YiairlEznM+fCOl8l2zMIsovGYdbGoJzD7ES
Ei6FDMuTeNSprK2Y23m/wVdEpRPoGoM0VhCWf7IoEK9xObOdf5fIpr9K5CF3o16uZp8ScROuEgnd
CBIlKS+Ru8TjzP8G6VA8Q9T1mk1q+3bDbFt1qLbaBonQla4xwv0upiB9FkPuuUH8J8YDiVaGKyIl
BY/nwaLbd1JMQKo0N3c5g0gN2B8wHKtZLxGzbnYqi0VbjLIkGM4G5L2WQ5gqw1lYka1mFy/oVW5z
LWiwEe0x+6dTma1dGO5n5Zp6wE9OC89Q0E80j3fxsZ6ivpAByIFKOeb4kk0hGLBozNeTtG56iZsb
jisSyUCSW3gtkXa5aU9UicTZft0rRdF5jZ2uhU8VJsJwarUSqTc1TOaiWI1bwygXXq2JIG2N9UPq
XUUBTA2nqrMa1dbjbIxhDMXERZmAXNdaZa4ZfQVl2/bF9OQaUojjiekQaFhMQkv2Gi2saEubvRVE
bfIaGGFNi4037jZ0mMIkuCL0xDlY8DMgTMqi+RSjIvOGKoUVfBFRjwN2sqFMdIp5pQRnLNa0Wfzo
sTaVLROpXCdnF5XrXhWnsp8oJaKTE+nNYFwuinLYi/wnIQ2nL3ADncJYoa6aHanVhjZ3K05q09a0
kTadIl/SVtfsnniaaLryI4YHFieUz06uPvWfXcGzrG2T++oRj1OI//wu+MfZrQ+H+/+tLI3p66ja
atuHSGvbyHVEcWmtnolL35njyWsxPB5FYGccJhfdfCgOEtpSN2Y960k6bX5lpFtD1xaQabYKK0jr
DHr/KKHE1qeJnYPhDQsCDvds/KSOcJSdUQ//MhaateIKKDQU2tXCnOsO9Fjy6An5ciKa31/04hhC
5ATixdr8TurkHN/QiI4hxCZS7iXYwmcZXnJt6XJtmd7IatkNGliNOlh2p/KG9BE5jH0hOfOOoKgd
KPP4zoFx9DrZj5i9CjoPkKSvOPwfglW1RvaoOTLNwK5Si+7H+hXy88TEJBaIkOkA5Avz4SDKCkfn
Yms/S3h5VNgkMLQTxPZ2Oe8qncrq+0nnL/NYJD+uFAAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2014 v4.1.72
     Generated on:       10/15/2014 11:00 PM
     Generated by:       Shane
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2014
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

function OnApplicationLoad {
	#Note: This function is not called in Projects
	#Note: This function runs before the form is created
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Windows Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#Important: Form controls cannot be accessed in this function
	#TODO: Add snapins and custom code to validate the application load
	
	$global:ExecutionComputer = "mscserver.msc.com"
	$RestoreAccount = "msc\Administrator"
	$RestoreAccountPassword = "adminpw"
	$global:SolutionsPath = "C:\Course1535\Solutions\"
	$global:RestoreScriptName = "HelpTeam.ps1"
	
	$secpasswd = ConvertTo-SecureString $RestoreAccountPassword -AsPlainText -Force
	$global:AdminCreds = New-Object System.Management.Automation.PSCredential($RestoreAccount, $secpasswd)
	
	return $true #return true for success or false for failure
}

function OnApplicationExit {
	#Note: This function is not called in Projects
	#Note: This function runs after the form is closed
	#TODO: Add custom code to clean up and unload snapins when the application exits
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-RestoreForm_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load("mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
	[void][reflection.assembly]::Load("System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
	[void][reflection.assembly]::Load("System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formExerciseRestore = New-Object 'System.Windows.Forms.Form'
	$labelResults = New-Object 'System.Windows.Forms.Label'
	$textboxTeam = New-Object 'System.Windows.Forms.TextBox'
	$comboboxExercise = New-Object 'System.Windows.Forms.ComboBox'
	$buttonClose = New-Object 'System.Windows.Forms.Button'
	$buttonRestore = New-Object 'System.Windows.Forms.Button'
	$labelExerciseToRestore = New-Object 'System.Windows.Forms.Label'
	$labelTeam = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	
	
	
	
	
	
	$formExerciseRestore_Load={
		#Initialize Form Controls here
		
		#Grab WS name to seed team number, i.e. Student20
		$teamnumber = ($env:computername) -ireplace "Student",""
		$textboxTeam.Text = $teamnumber
		
		#Enumerate child folders for exercise list
		$exercises = Invoke-Command -ComputerName $global:ExecutionComputer `
									-ArgumentList $global:SolutionsPath `
									-ScriptBlock { Get-ChildItem -Path $Args[0] -Directory } `
									-Credential $global:AdminCreds
		$exercises | ForEach-Object {
			$comboboxExercise.Items.Add($_.Name)
		}
	}
	
	$buttonClose_Click={
		$formExerciseRestore.Close()
	}
	
	$buttonRestore_Click={
		
		$buttonRestore.Enabled = $false
		
		$team = $textboxTeam.Text
		$exercise = $comboboxExercise.Text
		$RestoreScriptFull = Join-Path $global:SolutionsPath $global:RestoreScriptName
		
		$labelResults.text = "Invoking restore script on server.  Please wait..."
		$formExerciseRestore.Update()
		
		Invoke-Command `
		-ArgumentList $exercise, $team, $RestoreScriptFull `
		-ScriptBlock { param ($exercise, $team, $RestoreScriptFull) &($RestoreScriptFull) -team $team -exercise $exercise } `
		-ComputerName $executioncomputer -Authentication CredSSP `
		-Credential $AdminCreds
		
		$labelResults.text = "Restore complete.  Check the PowerShell console for errors."
		
		$buttonRestore.Enabled = $True
		
		
	}
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formExerciseRestore.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonClose.remove_Click($buttonClose_Click)
			$buttonRestore.remove_Click($buttonRestore_Click)
			$formExerciseRestore.remove_Load($formExerciseRestore_Load)
			$formExerciseRestore.remove_Load($Form_StateCorrection_Load)
			$formExerciseRestore.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formExerciseRestore.SuspendLayout()
	#
	# formExerciseRestore
	#
	$formExerciseRestore.Controls.Add($labelResults)
	$formExerciseRestore.Controls.Add($textboxTeam)
	$formExerciseRestore.Controls.Add($comboboxExercise)
	$formExerciseRestore.Controls.Add($buttonClose)
	$formExerciseRestore.Controls.Add($buttonRestore)
	$formExerciseRestore.Controls.Add($labelExerciseToRestore)
	$formExerciseRestore.Controls.Add($labelTeam)
	$formExerciseRestore.ClientSize = '374, 141'
	$formExerciseRestore.Name = "formExerciseRestore"
	$formExerciseRestore.Text = "Exercise Restore"
	$formExerciseRestore.add_Load($formExerciseRestore_Load)
	#
	# labelResults
	#
	$labelResults.BorderStyle = 'FixedSingle'
	$labelResults.Font = "Courier New, 9.75pt, style=Italic"
	$labelResults.Location = '22, 47'
	$labelResults.Name = "labelResults"
	$labelResults.Size = '327, 49'
	$labelResults.TabIndex = 0
	$labelResults.TextAlign = 'TopCenter'
	#
	# textboxTeam
	#
	$textboxTeam.Location = '68, 13'
	$textboxTeam.Name = "textboxTeam"
	$textboxTeam.Size = '60, 20'
	$textboxTeam.TabIndex = 1
	#
	# comboboxExercise
	#
	$comboboxExercise.FormattingEnabled = $True
	$comboboxExercise.Location = '268, 12'
	$comboboxExercise.Name = "comboboxExercise"
	$comboboxExercise.Size = '81, 21'
	$comboboxExercise.TabIndex = 2
	#
	# buttonClose
	#
	$buttonClose.Anchor = 'Bottom'
	$buttonClose.Location = '204, 106'
	$buttonClose.Name = "buttonClose"
	$buttonClose.Size = '75, 23'
	$buttonClose.TabIndex = 4
	$buttonClose.Text = "Close"
	$buttonClose.UseVisualStyleBackColor = $True
	$buttonClose.add_Click($buttonClose_Click)
	#
	# buttonRestore
	#
	$buttonRestore.Anchor = 'Bottom'
	$buttonRestore.Location = '95, 106'
	$buttonRestore.Name = "buttonRestore"
	$buttonRestore.Size = '75, 23'
	$buttonRestore.TabIndex = 3
	$buttonRestore.Text = "Restore"
	$buttonRestore.UseVisualStyleBackColor = $True
	$buttonRestore.add_Click($buttonRestore_Click)
	#
	# labelExerciseToRestore
	#
	$labelExerciseToRestore.Location = '144, 11'
	$labelExerciseToRestore.Name = "labelExerciseToRestore"
	$labelExerciseToRestore.Size = '118, 23'
	$labelExerciseToRestore.TabIndex = 1
	$labelExerciseToRestore.Text = "Exercise to Restore"
	$labelExerciseToRestore.TextAlign = 'MiddleRight'
	#
	# labelTeam
	#
	$labelTeam.Location = '12, 11'
	$labelTeam.Name = "labelTeam"
	$labelTeam.Size = '50, 23'
	$labelTeam.TabIndex = 0
	$labelTeam.Text = "Team #"
	$labelTeam.TextAlign = 'MiddleRight'
	$formExerciseRestore.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formExerciseRestore.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formExerciseRestore.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formExerciseRestore.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formExerciseRestore.ShowDialog()

} #End Function

#Call OnApplicationLoad to initialize
if((OnApplicationLoad) -eq $true)
{
	#Call the form
	Call-RestoreForm_psf | Out-Null
	#Perform cleanup
	OnApplicationExit
}
